-- group by

-- Give me the count of the number of product within each category
select CategoryID,count(*) as prod_count
from products
group by categoryid;

-- how many units of each product have been sold
select
 ProductID,
 sum(Quantity) as Total_Qty
from order_items
group by ProductID;

-- what is the total sales value generated by each product

select 
  ProductID,
  sum(total) as Total_sales
from order_items
group by ProductID;

-- what was the average selling price at which each product was sold

select 
 productid,
 avg(sellingprice)as avg_selling_price
from order_items
group by ProductID;

-- product sales summary

select 
 productid,
 count(*)as no_sales,
 sum(total) as total_sales,
 round(avg(total),2)as avg_sales ,
 min(total)as min_sales,
 max(total)as max_sales
from order_items
group by ProductID ;

-- for each customer ,how many order are there for each of their different order status
select
 customerid,
 Status,
 count(*) as no_order
 from orders
 group by customerid,Status;


use sql_ml;

/*
order by
select ....
from table...
order by column(s)

default order --> ascending 
*/
-- suppose we want product from the lowest selling price.
select 
productid,
sellingprice
from products
order by SellingPrice asc;

-- show the most expensive products first.
select 
 productname,
 SellingPrice
 from products
 order by SellingPrice desc;
 
 -- Display all product alphabetically
 
 select *
 from products
 order by productname asc;
 
 -- oldest customer -> youngest customers
 select 
  name,
  age
  from customers
  order by age desc;
 
-- sort product from most expensive selling price to least expensive

select 
productid,
sellingprice
from products
order by SellingPrice desc;

-- show the top 10 most expensive products

select 
 productid,
 productname,
 sellingprice
 from products
 order by sellingprice desc
 limit 10;
 
 -- the ten least expensive product
 select 
 productid,
 productname,
 sellingprice
 from products
 order by sellingprice asc
 limit 10;
 
 -- which inventory records have the lowest stock
 select 
  productid,
  stock
from inventory
order by stock asc;

-- show the top 5 most valuable payments.
select 
  paymentid,
  amount
from payments
order by amount desc
limit 5;

select *
from payments
order by amount desc
limit 5;

-- sorting order item by sales values

select 
 orderid,
 ProductID,
 total
from order_items
order by total  desc;

select *
from order_items
order by total  asc;

-- show the highest-rated review first.

select  *
from reviews
order by rating desc;  -- only 1 data can be present 

--  show product with MRP above 1000 ,starting with the most expensive.

select 
 productid,
 productname,
 mrp
 from products
 where mrp >1000
 order by mrp desc;
 
 select *
 from products
 where mrp >1000
 order by mrp desc;
 
 
 -- find the 5 cheapest(smallest) product whose mrp is above 700.
 select * 
 from products
 where mrp >700
 order by mrp asc
 limit 5;
 
 -- suppliers with the largest product catalog(differnt types of product) first.
 select 
  SupplierID,
  count(*)as catalog_size
 from products
 group by SupplierID
 order by catalog_size desc;
 
 -- which 5 supplier provide the largest number of products
 select 
  SupplierID,
  count(*)as catalog_size
 from products
 group by SupplierID
 order by catalog_size desc
 limit 5;
 
 -- top 5 product by total sales

select 
 productid,
 sum(total)as total_sales
from order_items
group by ProductID
order by total_sales desc
limit 5;
 
 -- sort product by category first and within each category sort by selling price  from highest to lowest
 
 select *
 from products
 order by categoryid asc,SellingPrice desc;
 
 use sql_ml;
 
 -- which payment method represent the highest total payment amount
 
 select * from payments;
 
 select 
   method,
   sum(amount) as total_payment
from payments
group by method
order by total_payment  desc
limit 5;

-- sort customer by city alphabetically and within each city sort customers by age from oldest to youngest
select 
 name,
 city,
 age
from customers
order by city  asc , age desc;

select *
from customers
order by city  asc , age desc;

/* Display the suppliers id with highest no of product 
first .it tied ,highest avg selling price first
*/
select 
 supplierid,
 count(*) as No_of_Product,
 avg(sellingprice) as avg_selling_Price
 from products
 group by SupplierID
 order by No_of_product asc, avg_Selling_price  desc;
 
-- sort product by category first and within each category sort by selling price from highest to lowest.

select *
from products 
order by CategoryID, SellingPrice desc;